# Custom Layers

In [2]:
import tensorflow as tf

tf.enable_eager_execution()

## Layers

In [3]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [4]:
# To use a layer, call it
layer(tf.zeros([10,5]))

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [8]:
# list all variables in a layer
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.12770557,  0.2307359 , -0.0403192 ,  0.09932238,  0.08584923,
          0.14230454,  0.2191782 ,  0.25919056, -0.14737967, -0.47755888],
        [-0.04376292,  0.60844284, -0.5908312 ,  0.621779  , -0.602178  ,
          0.05780369, -0.4876859 ,  0.60180825, -0.5969964 , -0.43179315],
        [ 0.41410893,  0.20090318,  0.5438672 ,  0.52475876, -0.51408154,
          0.06034338,  0.54363924,  0.45899898,  0.38624746,  0.5524588 ],
        [-0.44678026,  0.04302436,  0.6201065 ,  0.40708405,  0.07620323,
          0.54987293,  0.55514365,  0.52624995,  0.43963617,  0.18142861],
        [ 0.00332552,  0.61199695,  0.06096512, -0.12154782,  0.11804408,
          0.4675761 ,  0.08842731, -0.5093502 ,  0.35573572,  0.00415152]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [11]:
# Access variabels though accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.12770557,  0.2307359 , -0.0403192 ,  0.09932238,  0.08584923,
          0.14230454,  0.2191782 ,  0.25919056, -0.14737967, -0.47755888],
        [-0.04376292,  0.60844284, -0.5908312 ,  0.621779  , -0.602178  ,
          0.05780369, -0.4876859 ,  0.60180825, -0.5969964 , -0.43179315],
        [ 0.41410893,  0.20090318,  0.5438672 ,  0.52475876, -0.51408154,
          0.06034338,  0.54363924,  0.45899898,  0.38624746,  0.5524588 ],
        [-0.44678026,  0.04302436,  0.6201065 ,  0.40708405,  0.07620323,
          0.54987293,  0.55514365,  0.52624995,  0.43963617,  0.18142861],
        [ 0.00332552,  0.61199695,  0.06096512, -0.12154782,  0.11804408,
          0.4675761 ,  0.08842731, -0.5093502 ,  0.35573572,  0.00415152]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

Implementing Custom Layers

In [12]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape):
        self.kernel = self.add_variable("kernel", shape=[int(input_shape[-1]), self.num_outputs])
        
    def call(self, input):
        return tf.matmul(input, self.kernel)
    
layer = MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.14071372, -0.11052513,  0.01682729, -0.58071613,  0.05693603,
         0.2982003 , -0.31013483,  0.20942348, -0.30298907,  0.01218408],
       [ 0.07127047,  0.13432461, -0.44963816, -0.0424782 , -0.2848401 ,
        -0.02505952,  0.5020161 , -0.06956208,  0.59312004,  0.38921255],
       [-0.41053885,  0.15679628,  0.3309585 ,  0.5385017 , -0.13413614,
        -0.3767295 , -0.2692221 ,  0.11244905, -0.48692772,  0.37103504],
       [ 0.30584955,  0.20286989, -0.20842907,  0.53344256,  0.24092501,
         0.06268156,  0.35828584, -0

## Models: Composing Layers

In [14]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters
    
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)
        
        x += input_tensor
        return tf.nn.relu(x)
    
block = ResnetIdentityBlock(1, [1,2,3])
print(block(tf.zeros([1,2,3,3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_1/conv2d_3/kernel:0', 'resnet_identity_block_1/conv2d_3/bias:0', 'resnet_identity_block_1/batch_normalization_v1_3/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_3/beta:0', 'resnet_identity_block_1/conv2d_4/kernel:0', 'resnet_identity_block_1/conv2d_4/bias:0', 'resnet_identity_block_1/batch_normalization_v1_4/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_4/beta:0', 'resnet_identity_block_1/conv2d_5/kernel:0', 'resnet_identity_block_1/conv2d_5/bias:0', 'resnet_identity_block_1/batch_normalization_v1_5/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_5/beta:0']
